spring.application.name=LLM_SVC
server.port=8080
database=neo4j
spring.ai.ollama.base-url=${LLM_API_URL:http://host.docker.internal:11434}
spring.ai.ollama.chat.model=llama3.2
checkwx.api.url=https://api.checkwx.com/metar/{station}/decoded
checkwx.api.key=8bf1b3467a3548a1bb8b643978
aviation.weather.api.url=https://aviationweather.gov/api/data/windtemp?region=all